#! /usr/bin/env bash

filename=
query=

case $# in
  0)
    filename="$BIBTEX_FZF_DEFAULT_BIB_FILE"
    ;;
  1)
    filename="$1"
    ;;
  2)
    filename="$1"
    query="$2"
    ;;
esac

if [[ -z "$filename" ]]; then
  printf "Usage: %s [<filename>] [<query>]\n" "$(basename $0)"
  printf "No arguments: opens \$BIBTEX_FZF_DEFAULT_BIB_FILE\n" "$(basename $0)"
  exit 1
fi

script_dir="$(dirname "$(realpath "$0")")"
parsebib="$script_dir"/run-parsebib

header=$(cat << END
↩ : copy key · ^O: open attached file
END
)

choose() {
  fzf --header="$header" --reverse --expect=ctrl-o --query="$query"
}

line=$(
  "$parsebib" "$filename" |
  choose
) || exit 0

mode=$(head -1 <<< "$line")
key=$(tail -1 <<< "$line" | { read key _ ; echo $key ; })

case $mode in
  ctrl-o)
    bib_dirname="$(dirname "$1")"
    filename=$(
      cd "$bib_dirname" &&
      find . -name '*'"$key"'*.pdf' |
      sed 's/^\.\///' |
      fzf --reverse --select-1
    ) && open "$bib_dirname"/"$filename"
    ;;
  *)
    printf "%s" "$key" | pbcopy
    printf "Copied key \`%s\` to clipboard.\n" "$key"
    ;;
esac
