#! /usr/bin/env bash

if [[ $# -ne 1 ]] && [[ $# -ne 2 ]]; then
  printf "Usage: %s <filename> [<query>]\n" "$(basename $0)"
  exit 1
fi

script_dir="$(dirname "$(realpath "$0")")"
parsebib="$script_dir"/run-parsebib

query="$2"

header=$(cat << END
↩ : copy key · ^O: open attached file
END
)

choose() {
  fzf --header="$header" --reverse --expect=ctrl-o --query="$query"
}

line=$(
  "$parsebib" "$1" |
  choose
) || exit 0

mode=$(head -1 <<< "$line")
key=$(tail -1 <<< "$line" | { read key _ ; echo $key ; })

case $mode in
  ctrl-o)
    bib_dirname="$(dirname "$1")"
    filename=$(
      cd "$bib_dirname" &&
      find . -name '*'"$key"'*.pdf' |
      fzf --reverse --select-1
    ) && open "$filename"
    ;;
  *)
    printf "%s" "$key" | pbcopy
    printf "Copied key \`%s\` to clipboard.\n" "$key"
    ;;
esac
